import Head from 'next/head';
import Image from 'next/image';

import {
  Container,
  Header,
  Logo,
  Content,
  Card,
  ActionsContainer,
  InputButton,
} from './styles';

import newRoomIcon from '../../public/new_room_icon.svg';
import existingRoomIcon from '../../public/existing_room_icon.svg';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Meet.me - Your go-to meeting app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <Header>
          <Logo>meet.me</Logo>
        </Header>

        <Content>
          <Card>
            <Image src={newRoomIcon} alt="New room illustration" />

            <ActionsContainer>
              <p>New room</p>

              <button type="button">Create</button>
            </ActionsContainer>
          </Card>
          <Card>
            <Image src={existingRoomIcon} alt="Existing room illustration" />

            <ActionsContainer>
              <p>Existing room</p>

              <InputButton>
                <input type="number" placeholder="enter room id" step="0.01" />
                <button type="button">Join</button>
              </InputButton>
            </ActionsContainer>
          </Card>
        </Content>
      </Container>
    </div>
  );
}
