import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Meet.me - Your go-to meeting app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hello, world</h1>
      </main>
    </div>
  );
}
